#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?: .+$"
if ! [[ $message =~ $requiredPattern ]];
then
    echo ""
    echo -e "\033[1m\033[31m✘ Wrong commit message!\033[0m 😕"
    echo -e "\033[1mThe commit message must have this format:\033[0m"
    echo -e "\033[1m<type>[optional scope]: <description>\033[0m"
    echo ""
    echo -e "Allowed types:"
    echo -e "\033[36mbuild, chore, ci, docs, feat, fix, perf, refactor, revert, style, test\033[0m"
    echo ""
    echo -e "Examples:"
    echo -e "\033[32mfeat: add login button\033[0m"
    echo -e "\033[32mfix: typo in header\033[0m"
    echo ""
    echo -e "For more information on conventional commits, please see:"
    echo -e "\033[34mhttps://www.conventionalcommits.org/\033[0m"
    echo ""
    echo -e "Your commit message was:"
    echo "$message"
    echo ""
    echo -e "For more information, check script in .husky/commit-msg"
    echo ""
    exit 1
fi
