#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?: .+$"
if ! [[ $message =~ $requiredPattern ]];
then
    echo "-"
    echo "-"
    echo "-"
    echo "🚨 Wrong commit message! 😕"
    echo "The commit message must have this format:"
    echo "<type>[optional scope]: <description>"
    echo ""
    echo "Allowed types:"
    echo "build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test"
    echo ""
    echo "Examples:"
    echo "feat: add login button"
    echo "fix: typo in header"
    echo ""
    echo "For more information on conventional commits, please see:"
    echo "https://www.conventionalcommits.org/"
    echo ""
    echo "Your commit message was:"
    echo "$message"
    echo "-"
    echo "For more information, check script in .husky/commit-msg"
    echo "-"
    exit 1
fi
